version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: web/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
      - ./agent:/app/agent
      - ./tools:/app/tools
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    networks:
      - app-network

  frontend:
    build:
      context: web/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_WS_BASE_URL=ws://localhost:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  storage:
